version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm ci --legacy-peer-deps

  build:
    commands:
      - echo Building Vue project...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: no